config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    resources :relationships
  end
  resources :posts do
    resources :comments
  end
 

  root 'home#index'

  get '/home' => 'home#home'

  get '/globalcaws' => 'home#globalcaws'
  

  post '/log-in' => 'sessions#create'

  get '/sign-out' => 'sessions#destroy'

  get 'posts/create' => 'posts#create'

  get 'posts/show' => 'user#show'

  get 'posts/update'

  delete 'posts/:id' => 'posts#destroy'

  get '/users/:id' => 'users#show'

  get '/users' => 'users#index'

  get 'users/new' => 'users#new'

  get 'users/create'

  get 'users/edit'

  post '/users/:user_id/relationships' => 'relationships#create'

  delete '/users/:user_id/relationships/:id' => 'relationships#destroy'

  put '/profiles/:id/update' => 'profiles#update', as: :profile_update

  post '/deleteself' => 'users#destroy'

  post '/posts/:post_id/comments' => 'comments#create'

  get 'comments/edit'

  get '/posts/:post_id/comments/:id' => 'comments#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	def create!
	end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :profile
	has_many :posts
	has_many :comments
	has_many :active_relationships, class_name: "Relationship",
	foreign_key: "follower_id",
	dependent: :destroy
	has_many :passive_relationships, class_name: "Relationship",
	foreign_key: "followed_id",
	dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower

	validates :email, uniqueness: true
	validates :username, uniqueness: true

	def follow!(other_user)
		active_relationships.create(followed_id: other_user.id)
	end

	def unfollow!(other_user)
		active_relationships.find_by(followed_id: other_user.id).destroy
	end

	def following?(other_user)
		following.include?(other_user)
	end

	def followers_posts
		all_posts = []
		@following = self.following
		@following.each do |s|
			@posts = s.posts
			@posts.each do |put|
				all_posts << put
			end
		end
		all_posts
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  def current_user
  	if session[:user_id]
  		@current_user = User.find(session[:user_id])
    else
      redirect_to root_path
      flash[:notice] = "Please Sign in"
    end
  end
  
  @to_follow = User.all.each
  @post = Post.new
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	post_id = Post.find(params[:post_id])
  	c = Comment.create(params[:comment])
  	c.user_id = current_user.id
  	post_id.comments.push(c)
  	puts "*****************************"
  	puts @comment
  	puts "*****************************"
  	redirect_to (:back)
  end

  def edit
  end

  def destroy
  	comment = Comment.find(params[:id])
  	comment.destroy
  	redirect_to (:back)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "main"

	def index
		@comment = Comment.new
		@user = User.new
	end

	def home
		current_user
		@comment = Comment.new
		@user = User.new
		@post = Post.new
		@current_user_followers = @current_user.followers_posts.reverse.each
	end

	def globalcaws
		current_user
		@comment = Comment.new
		@user = User.new
		@post = Post.new
	end
	
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    new_post = Post.create(params[:post])
    current_user.posts.push(new_post)
  	redirect_to (:back) 
  end

  def show
  end

  def update
  end

  def destroy
    @post = params[:id]
    Post.destroy(@post)
    redirect_to user_path current_user
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def update
		puts "***********************"
		puts current_user.profile
		puts "***********************"
		@update = params[:form_fields]
		@current_user.profile.update(@update)
		redirect_to user_path
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def create
		@other_user = User.find(params[:user_id])
		current_user.follow!(@other_user)
		redirect_to (:back)
	end

	def destroy
		@other_user = User.find(params[:user_id])
		current_user.unfollow!(@other_user)
		redirect_to (:back)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		puts params[:user]
		@user = User.where(username: params[:username]).first
		if @user && @user.password == params[:password]
			session[:user_id] = @user.id
			puts "*******************"
			puts session[:user_id]
			puts "*******************"
			redirect_to home_path current_user
		else
			flash[:notice] = 'Incorrect Username/Password. Please try again.'
			redirect_to (:back)
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "main"

  def index
  	@users = User.all
  end
  def new 
  	@user = User.new
  end

  def show
    current_user
  	@post =Post.new
    @comment = Comment.new
  end

  def create
    # Take params from new.html.erb
  	@user = User.create(params[:user])
    # Create a profile for @new_user
    @profile = Profile.create(user_id: @user.id)
    @profile = @user.profile
    # Redirect to the new_user's profile page.
  	redirect_to root_path
  end

  def edit

  end
  
  def destroy
    @user = User.find(current_user[:id])
    @user.destroy
    session.clear
    redirect_to root_path
  end 

private 
  def user_params
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def all_posts
		Post.all.each do |post| 
 			content_tag :div do 
			post.user.username 
			post.title
			post.content 
			end 
		end 
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def posts
		html= ""
		def render(post)
			content_tag :div, class: "hover_div" do 
				content_tag :div, class: "all_post_div" do 
					content_tag :strong, class: "full_name" do
						post.user.fname + ' ' + post.user.lname 
					end
					post.user.username 
					content_tag :h4, class: "post_title_heading" do 
						post.title.upcase 
					end
					content_tag :p, class: "post_content" do
						post.content
					end
					post.comments.all.each do |comment| 
						content_tag :div, class: "all_comments_div" do 
							content_tag :p, class: "comment_content" do
								comment.content
							end
							if @current_user.id == comment.user_id 
								button_to "Delete Comment", post_comment_path(post.id, comment.id), method: :delete, class: "delete_comment_button" 
							end 
						end 
					end 
					button_tag "Leave Comment", class: "leave_comment_button" 
					form_for @comment, url: post_comments_path(post.id), html: {class: "post_comment_form"} do |c| 
						content_tag :div, class: "post_comment_div" do 
							c.text_field :content 
							c.submit "Comment" 
						end 
					end 
					if @current_user.id == post.user.id 
						button_to "Delete Post", post_path(post.id), method: :delete, class: "delete_post_button" 
					end 
				end
			end
		end
		Post.all.reverse.each do |posts| 
			html << render(posts)
		end 
		html.html_safe
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/globalcaws.html.erb
<% content_for :feed do %>
	<%= form_for @post do |f| %>
		<%= f.text_field :title, placeholder: "Title" %>
		<br>
		<%= f.text_field :content, placeholder: "Content" %>
		<%= f.submit :create %>
	<% end %>
	<% Post.all.reverse.each do |post| %>
		<%= content_tag :div, class: "hover_div" do %>
			<%= content_tag :div, class: "all_post_div" do %>
				<strong class="full_name"><%= post.user.fname + ' ' + post.user.lname %></strong>
				<%= '| ' + post.user.username %>
				<h4 class="post_title_heading"><%= post.title.upcase %></h4>
				<p class="post_content"><%= post.content %></p>
				<% post.comments.all.each do |comment| %>
					<%= content_tag :div, class: "all_comments_div" do %>
						<p class="comment_content"><%= comment.content %><span> - <%= comment.user.username %></span></p>
						<% if @current_user.id == comment.user_id %>
							<%= button_to "Delete Comment", post_comment_path(post.id, comment.id), method: :delete, class: "delete_comment_button" %>
						<% end %>
					<% end %>
				<% end %>
				<%= button_tag "Leave Comment", class: "leave_comment_button" %>
				<%= form_for @comment, url: post_comments_path(post.id), html: {class: "post_comment_form"} do |c| %>
						<%= content_tag :div, class: "post_comment_div" do %>
							<%= c.text_field :content %>
							<%= c.submit "Comment" %>
						<% end %>
				<% end %>
					<% if @current_user.id == post.user.id %>
					<%= button_to "Delete Post", post_path(post.id), method: :delete, class: "delete_post_button" %>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/home/home.html.erb
<% content_for :feed do %>
	<%= form_for @post do |f| %>
		<%= f.text_field :title, placeholder: "Title" %>
		<br>
		<%= f.text_field :content, placeholder: "Content" %>
		<%= f.submit :create %>
	<% end %>
	<% @current_user.followers_posts.reverse.each do |post| %>
		<%= content_tag :div, class: "hover_div" do %>
			<%= content_tag :div, class: "all_post_div" do %>
				<strong class="full_name"><%= post.user.fname + ' ' + post.user.lname %></strong>
				<%= '| ' + post.user.username %>
				<h4 class="post_title_heading"><%= post.title.upcase %></h4>
				<p class="post_content"><%= post.content %></p>
				<% post.comments.all.each do |comment| %>
					<%= content_tag :div, class: "all_comments_div" do %>
						<p class="comment_content"><%= comment.content %><span> - <%= comment.user.username %></span></p>
						<% if @current_user.id == comment.user_id %>
							<%= button_to "Delete Comment", post_comment_path(post.id, comment.id), method: :delete, class: "delete_comment_button" %>
						<% end %>
					<% end %>
				<% end %>
				<%= button_tag "Leave Comment", class: "leave_comment_button" %>
				<%= form_for @comment, url: post_comments_path(post.id), html: {class: "post_comment_form"} do |c| %>
						<%= content_tag :div, class: "post_comment_div" do %>
							<%= c.text_field :content %>
							<%= c.submit "Comment" %>
						<% end %>
				<% end %>
					<% if @current_user.id == post.user.id %>
					<%= button_to "Delete Post", post_path(post.id), method: :delete, class: "delete_post_button" %>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/home/index.html.erb
<% content_for :feed do %>
<div class="landing_div">
	<h1>Welcome!</h1>
	<div class="landing_div_inners"><%= link_to("Create New User", users_new_path)%></div>
<div class="landing_div_inners">
	<h3>Log-in</h3>
		<%= flash.notice %>
	<%= form_tag ({controller: "sessions", action: "create", method: "post"}) do %>
		<%= label_tag "Username" %>
		<%= text_field_tag :username %>
		<%= label_tag "Password" %>
		<%= password_field_tag :password %>
		<%= submit_tag :Login %>
	<% end %>
</div>
</div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<%= form_tag '/deleteself', method: 'post' do %>
	<%= submit_tag :'Delete My Account' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |f| %>
	<div class="user">
	<%= f.fname %>
	<%= f.lname %>
	<%= f.email %> 
	<%= link_to("View Profile", user_path(f)) %> 
</div>
<% end %>

app/views/users/new.html.erb
<% content_for :feed do %>
	<h1>Sign up!</h1>
	<%= form_for @user do |f| %>
		<%= f.label "Username"%>
		<%= f.text_field :username%>
		<br>
		<%= f.label "First Name"%>
		<%= f.text_field :fname%>
		<br>
		<%= f.label "Last Name"%>
		<%= f.text_field :lname%>
		<br>
		<%= f.label "Email"%>
		<%= f.text_field :email%>
		<br>
		<%= f.label "Password"%>
		<%= f.password_field :password%>
		<%= f.submit :create%>
	<% end %>
<% end %>

app/views/users/show.html.erb
<% content_for :profile do %>
	<h1><%= @current_user.fname %>'s Profile</h1>
	<%= button_tag "Edit Profile", class: "edit_profile_button" %>
	<%= content_tag(:div, class: "user_profile_container") do %>
		<%= content_tag :p, class: "profile_fields" do %>
			<%= @current_user.fname + " " + @current_user.lname %>
		<% end %>
		<%= content_tag :p, class: "profile_fields" do %>		
			<%= @current_user.profile.biography %>
		<% end %>
		<%= content_tag :p, class: "profile_fields" do %>
			<%= @current_user.profile.age %>
		<% end %>
		<%= content_tag :p, class: "profile_fields" do %>
			<%= @current_user.profile.location %>
		<% end %>
		
	<% end %>

	<%= form_tag profile_update_path(@current_user.profile.id), method: :put, class: "edit_profile_container" do %>
			<%= content_tag :p, class: "edit_profile_fields" do %>
				<%= text_field_tag "form_fields[biography]", nil, placeholder: "Biography" %>
			<% end %>
			<%= content_tag :p, class: "edit_profile_fields" do %>
				<%= text_field_tag "form_fields[age]", nil, placeholder: "Age" %>
			<% end %>
			<%= content_tag :p, class: "edit_profile_fields" do %>
				<%= text_field_tag "form_fields[location]", nil, placeholder: "Location" %>
			<% end %>
			<%= submit_tag(value= "Edit")%>
		<% end %>
<% end %>

<% content_for :feed do %>
	<%= form_for @post do |f| %>
		<%= f.text_field :title, placeholder: "Title" %>
		<br>
		<%= f.text_field :content, placeholder: "Content" %>
		<%= f.submit :create %>
	<% end %>
	<% @current_user.posts.reverse.each do |post| %>
		<%= content_tag :div, class: "hover_div" do %>
			<%= content_tag :div, class: "all_post_div" do %>
				<strong class="full_name"><%= post.user.fname + ' ' + post.user.lname %></strong>
				<%= '| ' + post.user.username %>
				<h4 class="post_title_heading"><%= post.title.upcase %></h4>
				<p class="post_content"><%= post.content %></p>
				<% post.comments.all.each do |comment| %>
					<%= content_tag :div, class: "all_comments_div" do %>
						<p class="comment_content"><%= comment.content %></p>
						<% if @current_user.id == comment.user_id %>
							<%= button_to "Delete Comment", post_comment_path(post.id, comment.id), method: :delete, class: "delete_comment_button" %>
						<% end %>
					<% end %>
				<% end %>
				<%= button_tag "Leave Comment", class: "leave_comment_button" %>
				<%= form_for @comment, url: post_comments_path(post.id), html: {class: "post_comment_form"} do |c| %>
						<%= content_tag :div, class: "post_comment_div" do %>
							<%= c.text_field :content %>
							<%= c.submit "Comment" %>
						<% end %>
				<% end %>
					<% if @current_user.id == post.user.id %>
					<%= button_to "Delete Post", post_path(post.id), method: :delete, class: "delete_post_button" %>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
<% end %>