config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    resources :relationships
  end
  resources :posts do
    resources :comments
  end
 

  root 'home#index'

  get '/home' => 'home#home'

  get '/globalcaws' => 'home#globalcaws'
  

  post '/log-in' => 'sessions#create'

  get '/sign-out' => 'sessions#destroy'

  get 'posts/create' => 'posts#create'

  get 'posts/show' => 'user#show'

  get 'posts/update'

  delete 'posts/:id' => 'posts#destroy'

  get '/users/:id' => 'users#show'

  get '/users' => 'users#index'

  get 'users/new' => 'users#new'

  get 'users/create'

  get 'users/edit'

  post '/users/:user_id/relationships' => 'relationships#create'

  delete '/users/:user_id/relationships/:id' => 'relationships#destroy'

  put '/profiles/:id/update' => 'profiles#update', as: :profile_update

  post '/deleteself' => 'users#destroy'

  post '/posts/:post_id/comments' => 'comments#create'

  get 'comments/edit'

  get '/posts/:post_id/comments/:id' => 'comments#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	def create!
	end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :profile
	has_many :posts
	has_many :comments
	has_many :active_relationships, class_name: "Relationship",
	foreign_key: "follower_id",
	dependent: :destroy
	has_many :passive_relationships, class_name: "Relationship",
	foreign_key: "followed_id",
	dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower

	validates :email, uniqueness: true
	validates :username, uniqueness: true

	def follow!(other_user)
		active_relationships.create(followed_id: other_user.id)
	end

	def unfollow!(other_user)
		active_relationships.find_by(followed_id: other_user.id).destroy
	end

	def following?(other_user)
		following.include?(other_user)
	end

	def followers_posts
		all_posts = []
		@following = self.following
		@following.each do |s|
			@posts = s.posts
			@posts.each do |put|
				all_posts << put
			end
		end
		all_posts
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  def current_user
  	if session[:user_id]
  		@current_user = User.find(session[:user_id])
    else
      redirect_to root_path
      flash[:notice] = "Please Sign in"
    end
  end
  
  @to_follow = User.all.each
  @post = Post.new
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	post_id = Post.find(params[:post_id])
  	c = Comment.create(params[:comment])
  	c.user_id = current_user.id
  	post_id.comments.push(c)
  	puts "*****************************"
  	puts @comment
  	puts "*****************************"
  	redirect_to (:back)
  end

  def edit
  end

  def destroy
  	comment = Comment.find(params[:id])
  	comment.destroy
  	redirect_to (:back)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "main"

	def index
		@comment = Comment.new
		@user = User.new
	end

	def home
		current_user
		@comment = Comment.new
		@user = User.new
		@post = Post.new
		@current_user_followers = @current_user.followers_posts.reverse.each
	end

	def globalcaws
		current_user
		@comment = Comment.new
		@user = User.new
		@post = Post.new
	end
	
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    new_post = Post.create(params[:post])
    current_user.posts.push(new_post)
  	redirect_to (:back) 
  end

  def show
  end

  def update
  end

  def destroy
    @post = params[:id]
    Post.destroy(@post)
    redirect_to user_path current_user
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def update
		puts "***********************"
		puts current_user.profile
		puts "***********************"
		@update = params[:form_fields]
		@current_user.profile.update(@update)
		redirect_to user_path
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		puts params[:user]
		@user = User.where(username: params[:username]).first
		if @user && @user.password == params[:password]
			session[:user_id] = @user.id
			puts "*******************"
			puts session[:user_id]
			puts "*******************"
			redirect_to home_path current_user
		else
			flash[:notice] = 'Incorrect Username/Password. Please try again.'
			redirect_to (:back)
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "main"

  def index
  	@users = User.all
  end
  def new 
  	@user = User.new
  end

  def show
    current_user
  	@post =Post.new
    @comment = Comment.new
  end

  def create
    # Take params from new.html.erb
  	@user = User.create(params[:user])
    # Create a profile for @new_user
    @profile = Profile.create(user_id: @user.id)
    @profile = @user.profile
    # Redirect to the new_user's profile page.
  	redirect_to root_path
  end

  def edit

  end
  
  def destroy
    @user = User.find(current_user[:id])
    @user.destroy
    session.clear
    redirect_to root_path
  end 

private 
  def user_params
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def all_posts
		Post.all.each do |post| 
 			content_tag :div do 
			post.user.username 
			post.title
			post.content 
			end 
		end 
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def posts
		html= ""
		def render(post)
			content_tag :div, class: "hover_div" do 
				content_tag :div, class: "all_post_div" do 
					content_tag :strong, class: "full_name" do
						post.user.fname + ' ' + post.user.lname 
					end
					post.user.username 
					content_tag :h4, class: "post_title_heading" do 
						post.title.upcase 
					end
					content_tag :p, class: "post_content" do
						post.content
					end
					post.comments.all.each do |comment| 
						content_tag :div, class: "all_comments_div" do 
							content_tag :p, class: "comment_content" do
								comment.content
							end
							if @current_user.id == comment.user_id 
								button_to "Delete Comment", post_comment_path(post.id, comment.id), method: :delete, class: "delete_comment_button" 
							end 
						end 
					end 
					button_tag "Leave Comment", class: "leave_comment_button" 
					form_for @comment, url: post_comments_path(post.id), html: {class: "post_comment_form"} do |c| 
						content_tag :div, class: "post_comment_div" do 
							c.text_field :content 
							c.submit "Comment" 
						end 
					end 
					if @current_user.id == post.user.id 
						button_to "Delete Post", post_path(post.id), method: :delete, class: "delete_post_button" 
					end 
				end
			end
		end
		Post.all.reverse.each do |posts| 
			html << render(posts)
		end 
		html.html_safe
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
			<%= link_to("Home", {controller: "home", action: "home"}, class: "header_links") %>
			<%= link_to("Globalcaws", {controller: "home", action: "globalcaws"}, class: "header_links") %>
			<% if @current_user %>
				<%= link_to("Profile", @current_user, class: "header_links") %>
				<%= link_to("Sign-out", {controller: "sessions", action: "destroy", method: "post"}, class: "header_links") %>
		<% end %>
	</header>
	<div class="main_container">
		<div class= "inner_containers" id="profile_container">
			<%= content_tag :div, class: "inner_profile" do %>
				<%= image_tag "crow.png", class: "user_picture" %>
				<%= content_tag :div, class: "user_stats_container" do %>
					<% if @current_user %>
						<%= content_tag :div, class: "user_stats" do %>
							<%= content_tag :p, class: "stat_title" do %>
								following
							<% end %>
							<%= @current_user.following.count %>
						<% end %>
						<%= content_tag :div, class: "user_stats" do %>
							<%= content_tag :p, class: "stat_title" do %>
								followers
							<% end %>
							<%= @current_user.followers.count %>
						<% end %>
						<%= content_tag :div, class: "user_stats" do %>
							<%= content_tag :p, class: "stat_title" do %>
								posts
							<% end %>
							<%= @current_user.posts.count %>
						<% end %>
					<% end %>
				<% end %>
				<%= yield :profile %>
			<% end %>
		</div>
		<div class= "inner_containers" id="feed_container">
			<%= yield :feed %>
		</div>
		<div class= "inner_containers" id="followers_container">
			<%= content_tag :div, class: "inner_followers" do%>
				<% User.all.each do |user| %>
					<% if @current_user %>
					<% if user.id != @current_user.id  %>
							<%= content_tag :div, class: "user_list" do %>
								<%= image_tag("crow.png", class: "user_picture") %>
								<%= content_tag :h5, class: "full_name" do %>
									<%= user.username + " | " + user.fname + " " + user.lname %>
								<% end %>
								<% if @current_user.following?(user) %>
									<%= button_to "unfollow", user_relationship_path(user.id, @current_user.id), method: :delete, class: "exchange" %>
									<% else %>
									<%= button_to "follow", user_relationships_path(user.id), method: :post, class: "exchange" %>
								<% end %>
							<% end %>
						<% end %>
					<% end %>
				<% end %>
			<% end %>
		</div>
	</div>
</body>
</html>